### ISSUE TITLE
Error during overlay rendering

### ISSUE THREAD

**Issue by VygandasEidukis** [Matt12yearslater/max-hit#18]
Hey,
I've noticed that sometimes when I go to GE and sell something RL becomes unresponsive.
I don't know if that's exactly from GE, but it only happens once or twice / day without any other indication.

I've went to logs and saw this:
`2022-07-01 20:37:17 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - following log message logged 1000 times!
2022-07-01 20:37:17 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.maxhit.MaxHitPlugin.strengthBonus(MaxHitPlugin.java:716)
	at com.maxhit.MaxHitPlugin.maxHitBase(MaxHitPlugin.java:742)
	at com.maxhit.MaxHitOverlay.render(MaxHitOverlay.java:54)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:719)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlays(OverlayRenderer.java:322)
	at net.runelite.client.ui.overlay.OverlayRenderer.renderOverlayLayer(OverlayRenderer.java:229)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:444)
	at gg.ag(gg.java:4402)
	at jn.gm(jn.java:4595)
	at u.jw(u.java:10197)
	at u.jw(u.java:10228)
	at u.jw(u.java:10228)
	at u.jw(u.java:10228)
	at go.ju(go.java:10086)
	at client.ga(client.java:4436)
	at client.aj(client.java:1198)
	at ap.vr(ap.java:364)
	at ap.run(ap.java:318)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by Seebity** [comment]
This might've been fixed in the last update/hotfix
