### ISSUE TITLE
Not handling new league items (or perhaps "unknown" items?)

### ISSUE THREAD

**Issue by adamk33n3r** [Matt12yearslater/max-hit#27]
Getting this error and the overlay won't render. It's happening when I have leagues stuff equipped. Specifically I've noticed it with `Sage's Greaves` and `Fairy Mushroom`
```
12:54:33.105 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at com.maxhit.MaxHitPlugin.strengthBonus(MaxHitPlugin.java:715)
	at com.maxhit.MaxHitPlugin.maxHitBase(MaxHitPlugin.java:742)
	at com.maxhit.MaxHitOverlay.render(MaxHitOverlay.java:54)
```

**Comment by Aleckxszandre** [comment]
Also with League items: The overlay appears, but it does not update with Ruinous Powers prayers.
